- cmake/aws-crt-cpp-config.cmake
*Issue #, if available:* https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/pull/7
*Description of changes:* Added aws-c-cal as an export dependency to the cmake config template
> Added aws-c-cal as an export dependency to the cmake config template

- include/aws/crt/crypto/HMAC.h
- include/aws/crt/crypto/Hash.h
- include/aws/crt/mqtt/MqttClient.h
- samples/mqtt_pub_sub/main.cpp
- source/mqtt/MqttClient.cpp
I wanted to see if there were any OTHER mis-spellings in the public API so installed [code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker), perused the /include folder,  and fixing anything I saw with global find-replace. That's why so many unimportant comments and log-statements got sucked up into this PR.
> Fix spelling of OnConnectionInterupted

- include/aws/crt/io/TlsOptions.h
Fixed the InitClientWithMtlsPkcs12 function header for macOS.
> Fix InitClientWithMtlsPkcs12 function header.

- include/aws/crt/mqtt/MqttClient.h
- samples/mqtt_pub_sub/main.cpp
- source/mqtt/MqttClient.cpp
The underlying aws-c-mqtt implementation does not feature "connection state" as part of its public API, the user is informed of state changes via callbacks (OnConnected, OnConnectionInterrupted, OnConnectionResumed, OnDisconnect).
The state enum was meant here as a convenience feature, but it has introduced confusion, and it's not consistently implemented across the different language CRTs. If a public state enum is found to be desirable, it should be implemented in aws-c-mqtt and reflected consistently in all the language CRTs.
> Remove Mqtt::ConnectionState enum

- include/aws/crt/JsonObject.h
- include/aws/crt/Optional.h
- samples/mqtt_pub_sub/main.cpp
- source/JsonObject.cpp
- tests/CMakeLists.txt
- tests/JsonParserTest.cpp
- tests/OptionalMemorySafetyTest.cpp
> Fixed bug in Aws::Crt::Optional causing copies to cause memory errors.

- include/aws/crt/Types.h
- include/aws/crt/io/Stream.h
- source/io/Stream.cpp
- tests/CMakeLists.txt
- tests/StreamTest.cpp
Converts from basic C++ streams into aws-c streams, allowing users to use C++ streams as http request bodies.
This lets us give a C++ stream interface to the Http Request wrapper.
> Stream wrapper + tests

- CMakeLists.txt
- README.md
> Fixed default cmake build without a specified CMAKE_BUILD_TYPE.

- include/aws/crt/io/Bootstrap.h
- source/io/Bootstrap.cpp
- tests/ChannelBootstrapTest.cpp
- tests/CredentialsTest.cpp
- tests/HttpClientConnectionManagerTest.cpp
- tests/HttpClientTest.cpp
- tests/IotServiceTest.cpp
- tests/MqttClientTest.cpp
- tests/Sigv4SigningTest.cpp
Allow user to know when `ClientBootstrap` is done shutting down its behind-the-scenes resources.
User may register a `std::function<void()>` that fires upon shutdown complete. I considered offering a `std::future` to users, but realized you can only do blocking wait()/get() operations on a c++ future, you can't register a callback to fire (a feature available in Python and Java's future primitives). So if a user wants to use `std::future` they can hook that up themselves with the callback (I did this in a test).
Also added an `EnableBlockingShutdown()` function. I was looking around at how async-shutdown was handled in other `aws-crt-cpp` classes and saw this feature on the `HttpClientConnectionManager`. It's simplifies things when the IO classes are created on the main thread's stack …
> Bootstrap shutdown

- include/aws/crt/io/TlsOptions.h
- include/aws/iot/MqttClient.h
- source/io/TlsOptions.cpp
- source/iot/MqttClient.cpp
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/118
Hooking up functionality to set minimum TLS version in a couple of places.
> Exposing set minimum TLS version

- CMakeLists.txt
- bin/elasticurl_cpp/CMakeLists.txt
Currently aws-crt-cpp links with the dynamic runtime library on Windows. Trying to use the option `-DSTATIC_CRT=TRUE` produces a library with mixed runtimes and causes errors when trying to link it into a program. This is because the C parts use the static runtime as expected, but the C++ parts still use the default dynamic runtime.
This commit adds support for `STATIC_CRT` setting to aws-crt-cpp. A complementary commit (awslabs/aws-c-common#638) into aws-c-common is needed to make also the tests compile properly after this change.
----
> Support STATIC_CRT setting like aws-c-* libraries do

- source/io/TlsOptions.cpp
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/145
In the case that a TLS-context-new function returns null, a null pointer passed into a shared_ptr via reset causes a strong reference to null pointer.  This gets passed into aws_tls_ctx_destroy on clean_up, where it is dereferenced, causing a crash.
> Crash fix caused by passing null into a shared_ptr reset

- include/aws/crt/http/HttpRequestResponse.h
- source/http/HttpRequestResponse.cpp
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/146
If the underlying http_message get destroyed before the destructor of HttpMessage, it may crash when the destructor accesses the underlying http_message.
- Keep the underlying http_message alive until the destructor called
> add refcount for HttpMessage and remove ownMessage

- include/aws/crt/mqtt/MqttClient.h
- source/mqtt/MqttClient.cpp
- update submodules, gets aws-c-io with longer default TLS timeouts.
- expose `MqttConnection::SetReconnectTimeout(...)`
> Help with TLS timeout problems

- include/aws/crt/StringView.h
`using StringView = std::string_view` was not taken into effect for C++ 17 
because the code is nested under another  "__cplusplus < 201703L"
> Fix string_view in C++ 17

- CMakeLists.txt
- include/aws/crt/Api.h
- include/aws/crt/Types.h
- source/io/Stream.cpp
- tests/ChannelBootstrapTest.cpp
- tests/CredentialsTest.cpp
- tests/EventLoopGroupTest.cpp
- tests/HMACTest.cpp
- tests/HashTest.cpp
- tests/HostResolverTest.cpp
- tests/HttpClientConnectionManagerTest.cpp
- tests/HttpClientTest.cpp
- tests/HttpRequestTest.cpp
- tests/ImdsClientTest.cpp
- tests/IotServiceTest.cpp
- tests/JsonParserTest.cpp
- tests/MqttClientTest.cpp
- tests/OptionalMemorySafetyTest.cpp
- tests/Sigv4SigningTest.cpp
- tests/StreamTest.cpp
- tests/StringViewTest.cpp
- tests/TLSContextTest.cpp
- tests/TypesTest.cpp
- tests/UUIDTest.cpp
- tests/Utils.h
**Issue 1**:
> error C2491: 'Aws::Crt::ArrayListToVector': definition of dllimport function not allowed
```c++
// In include/aws/crt/Types.h
template <typename RawType, typename TargetType>
AWS_CRT_CPP_API Vector<TargetType> ArrayListToVector(const aws_array_list *array, TypeConvertor<RawType, TargetType> conv)
```
**Fix issue 1**:
Remove `AWS_CRT_CPP_API`
**Issue 2**:
> warning C4273: 'Aws::Crt::TestCleanupAndWait': inconsistent dll linkage
> warning LNK4217: locally defined symbol TestCleanupAndWait
```c++
// In both include/aws/crt/Api.h and tests/Utils.h
AWS_CRT_CPP_API void TestCleanupAndWait();
```
**Fix issue 2**:
1. Remove `TestCleanupAndWait` in `include/aws/crt/Api.h`
2. Remove `AWS_CRT_CPP_API` for `TestCleanupAndWait` in `tests/Utils.h`
3. `#include <Utils.h>` for all tests. …
> Fix symbol import/export issues on Windows.

- include/aws/crt/StlAllocator.h
Remove references to deprecated(17)/removed(20) std::allocator type members.  See http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0174r0.html#2.4
> C++20 compile fixes

- include/aws/crt/mqtt/MqttClient.h
- source/mqtt/MqttClient.cpp
* Exposed the underlying C mqtt_connection pointer via a method for use by the DeviceDefender code which will be implemented in the V2 SDK library.
* Updated the aws-c-mqtt library to a commit with memory leak and deadlock bug fixes.
> Exposing underlying mqtt connection. Updating c mqtt library commit.

- source/Api.cpp
- source/auth/Credentials.cpp
* Fixes a potential crash when assigning tls options for a proxied x509 credentials provider
> Fix crash when assigning tls options for x509 credentials provider

- codebuild/linux-integration-tests.yml
* now the code build job should succeed for all branches, not just Proxyv2
> Add proxy build spec to main

- source/Api.cpp
- tests/ApiTest.cpp
- tests/CMakeLists.txt
* Fix an issue with high resolution clock time calculations that would lead to stuck event loops and other issues when a Windows machine had been up longer than 21 days
* Fix an issue with CRT initialization/shutdown that led to a crash due to out-of-sync allocators.
> Windows high performance counter precision fix; crt init/shutdown fix

- include/aws/crt/io/TlsOptions.h
- source/io/TlsOptions.cpp
* Updates submodules for API tweak and mqtt fixes
* Adds mac key chain override API from https://github.com/awslabs/aws-crt-cpp/pull/239
> Sub and keychain

- source/Api.cpp
Since the eventstream library will have a C++ wrapper, it must also be initialized and cleaned inside the `ApiHandle` class.
> Initialize EventStream library in ApiHandle class

- include/aws/crt/external/cJSON.h
- source/JsonObject.cpp
- source/external/cJSON.cpp
**Issue:**
TT: https://t.corp.amazon.com/issues/D24933649
[CVE-2019-11834](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11834) cJSON before 1.7.11 allows out-of-bounds access, related to \x00 in a string literal.
[CVE-2019-11835](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11835) cJSON before 1.7.11 allows out-of-bounds access, related to multiline comments.
Upgrade cJSON dependency to version which addresses security isssue: https://github.com/DaveGamble/cJSON/releases/tag/v1.7.14
The PR has two commits:
1. A literally copy paste of `cJSON.h` and `cJSON.c` from https://github.com/DaveGamble/cJSON
2. Add customization back based on cJSON v1.7.14, including:
1. valueInt was moved up to improve alignment.
2. Wrap all symbols in the Aws …
> Upgrade cJSON from v1.7.7 to v1.7.14

- CMakeLists.txt
- include/aws/crt/io/TlsOptions.h
- include/aws/iot/MqttClient.h
- source/io/TlsOptions.cpp
- source/iot/MqttClient.cpp
`MqttClientConnectionConfigBuilder` wasn't properly checking for errors when creating the `TlsContext`
> Catch error when TlsContext fails.

- update-version.sh
> Try new way of tagging releases; currently stuck on a version 1.5 years old

- .github/workflows/ci.yml
**Issue:**
The "windows-vs14 (x86)" build wasn't doing what it claimed. It was just doing x64 builds with the latest Visual Studio.
Now it actually uses the 14.0 toolset and Win32 (aka "x86") architecture
> Fix Windows x86 CI

- source/io/TlsOptions.cpp
*Issue
aws_tls_connection_options_copy from aws-c-io changed the behavior that it will release dest tls option before copy. Update the aws-c-io library. 
Clean out uninitialized m_tls_connection_options in TlsConnectionOptions constructor
> Clean out m_tls_connection_options in TlsConnectionOptions constructor

- include/aws/crt/StringView.h
StringView.h has a constructor with a parameter length and a function with the same name. Old g++ (pre 5.0) flags it if -Wshadow is on.
Replace length parameter with count to make it consistent with c++17 std implementation and to avoid the shadow warning.
> fix shadow paramater warning on old g++

- include/aws/crt/io/TlsOptions.h
Related: https://github.com/awslabs/aws-c-io/pull/476
Custom keychain management is being deprecated starting in macOS 12. This was causing compiler warnings.
Therefore, mark the `TlsContextOptions.SetKeychainPath()` function as deprecated, which leads to these deprecated mac keychain functions being invoked.
> Deprecate macOS keychain path function.

- include/aws/crt/StringView.h
[aws-sdk-cpp-1858](https://github.com/aws/aws-sdk-cpp/issues/1858)
Although cpp 20 remains not officially supported, there are a few changes we can make to build cpp 20 on windows. One of them being this typo where we are supposed to import `string_view` if cpp > 17. in this instance there was a typo where `_MSC_LANG` is mispelled and it should be `_MSVC_LANG` ([docs](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170)). it only broke with cpp 20 because u8string hash was added in [cpp 20](https://en.cppreference.com/w/cpp/string/basic_string/hash)
```
template<> struct hash<[std::u8string](http://en.cppreference.com/w/cpp/string/basic_string)>;
template<> struct …
```
> Fixes cpp 20 builds for windows.

- tests/CMakeLists.txt
Fix comes by updating aws-c-io submodule: https://github.com/awslabs/aws-c-io/pull/461
> Fix memory leak from ApiHandle

- .github/workflows/ci.yml
- README.md
* Document how to build.
* Add CI job to ensure it builds.
* Unfortunately can't run tests in CI because we don't have access to an M1 cloud machine.
> Document building for Apple silicon (M1).

- include/aws/iot/MqttClient.h
- source/iot/MqttClient.cpp
Modified MQTT connection builder to allow custom authorizer support. Added missing username and password options, and also added a function to make a default builder. All of these changes make MQTT connection builder closer to the Java V2 SDK in option parity, as well as adding custom authorizer support.
______________
> MQTT builder custom authorizer support

- .github/workflows/docs.yml
Our Github workflows no longer have write permissions by default, so this job needs to be opted-in.
> Explicit permissions for update-docs-branch job

- CMakeLists.txt
- Adding support for config-version.cmake generation at the top level CMakeLists.txt
- Stripping starting v on version numbers on the update_version script
> Fix to cmake detection of CRT version by consumers

- .github/workflows/release.yml
A few months back, we restricted tightened person Github workflows to be read-only by default. That broke the "release" workflow, which pushes changes to `main`.
This should fix it
> Give write permissions to release.yml

- CMakeLists.txt
Update all submodules, including S2N-TLS and AWS-LC which we hadn't updated for a while due to issues which are now resolved (see https://github.com/awslabs/aws-c-common/pull/925).
> Use latest versions of S2N-TLS and AWS-LC

- include/aws/crt/endpoints/RuleEngine.h
- source/endpoints/RuleEngine.cpp
Remove unused allocator variable to fix build warning in cpp sdk
> remove unused variable

- CMakeLists.txt
CRT cmake script did not install new headers
Correct copy-paste typo.
> Fix a typo in cmake script for headers install

- include/aws/crt/io/TlsOptions.h
- source/io/TlsOptions.cpp
- tests/HttpClientConnectionManagerTest.cpp
- tests/TLSContextTest.cpp
N/A
Add support for configuring TLS Cipher Preferences (Eg Post-Quantum TLS Ciphers).
> Add Support for choosing PQ TLS Cipher Preferences

- include/aws/crt/RefCounted.h
- source/http/HttpRequestResponse.cpp
- This fixes an issue that aws_input_stream was being freed twice.
> Fix destruct http message double free

- bin/elasticurl_cpp/main.cpp
- source/Api.cpp
**Issue:**
HTTP integration tests were frequently failing
**Diagnosis:**
some integration tests defined in the aws-c-http submodule were hitting example.com, and these connections have been timing out pretty frequently lately
Update submodules. The tests in aws-c-http don't hit example.com anymore.
> Fix flaky tests

- README.md
**Issue:**
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/499
User encountering crashes when they build an application that used the IoT SDK and libcurl, which created a dependency on two different versions of libcrypto, which leads to crazy runtime crashes.
**Description of Changes:**
Explain the `-DUSE_OPENSSL=ON` build option, and when you'd want to use it.
> how to use system installation of libcrypto

- include/aws/crt/Optional.h
Checks if `std::optional` is available, and if so, alias `Aws::Crt::Optional<T>` to `std::optional<T>`.
Also, fix a missing `#include <type_traits>` when not aliasing, for `std::aligned_storage`.
> [Aws::Crt::Optional] avoid std::aligned_storage

- include/aws/crt/io/Stream.h
- source/io/Stream.cpp
- Clarify that ReadImpl() should only return false on failure. The docs were ambiguous about whether false meant "done" or "failed".
- Ensure that aws_raise_error() is raised if any ReadImpl() implementation fails to do so. The docs docs only say you "SHOULD" raise an error, and the 2 implementations I've seen don't bother to do so.
> Fix ambiguity around InputStream::ReadImpl() errors

- docsrc/Doxyfile
Fixes `index.md` not being included in the Doxygen source, causing the main page of the documentation generated by Doxygen to be blank. See https://awslabs.github.io/aws-crt-cpp/, while it should be the contents of https://github.com/awslabs/aws-crt-cpp/blob/main/docsrc/index.md
________
> Add the main page to the documentation

- .builder/actions/crt-ci-prep.py
- CMakeLists.txt
- bin/mqtt5_app/main.cpp
- bin/mqtt5_canary/main.cpp
- source/iot/Mqtt5Client.cpp
- source/mqtt/Mqtt5Client.cpp
- tests/Mqtt5ClientTest.cpp
1. As the latest c-common change added a way to skip a test. We enable the Mqtt5 Unit tests in the CI and skip it if the environment variable is not set
2. The Mqtt5 client and builder will now return nullptr on failure. 
> Enable MQTT5 client unit tests in CI and improve MQTT5 client error handling

- include/aws/iot/MqttClient.h
- source/iot/MqttClient.cpp
- tests/MqttClientTest.cpp
~~Minor adjustment to stay 100% fully backwards compatible with the MQTT311 custom authorizer API, even if it technically won't/shouldn't work with the old API.~~
Adjusts documentation to note that passing a custom authorizer signature with the old API will always fail.
_________
> Full backwards compat with custom auth in MQTT311

- .builder/actions/crt-ci-prep.py
- include/aws/iot/Mqtt5Client.h
- include/aws/iot/MqttClient.h
- include/aws/iot/MqttCommon.h
- source/iot/Mqtt5Client.cpp
- source/iot/MqttClient.cpp
- tests/CMakeLists.txt
- tests/MqttClientTest.cpp
Adds PKCS12 support to the MQTT311 and MQTT5 builders.
___________
> PKCS12 builder support

- codebuild/mqtt5-cpp-canary-test.yml
Bumps the version of the MQTT5 canary builder to the latest release.
___________
> Bump the MQTT5 canary builder version

- bin/mqtt5_canary/main.cpp
Use `PRInSTR` to specify the string length, otherwise it would cause buffer overflow with `fprintf`
> Fix format specifier in canary

- include/aws/crt/mqtt/Mqtt5Client.h
- include/aws/crt/mqtt/Mqtt5ClientCore.h
- include/aws/crt/mqtt/MqttClient.h
- include/aws/iot/Mqtt5Client.h
- source/mqtt/Mqtt5Client.cpp
- source/mqtt/Mqtt5ClientCore.cpp
- source/mqtt/MqttClient.cpp
- tests/CMakeLists.txt
- tests/Mqtt5ClientTest.cpp
Bind out the Mqtt5 to Mqtt3 adapter.
(Still need update submodules: https://github.com/awslabs/aws-c-mqtt/pull/313)
> Mqtt5to3 adapter 

- CMakeLists.txt
- README.md
- bin/elasticurl_cpp/CMakeLists.txt
- bin/mqtt5_app/CMakeLists.txt
- bin/mqtt5_canary/CMakeLists.txt
**Issue:**
The `-DSTATIC_CRT=ON` CMake option for choosing the MSVC runtime library didn't affect submodules. Also it's a terribly named option, since we refer to this codebase as "CRT".
1) Pick up this fix in the submodules: https://github.com/awslabs/aws-c-common/pull/1054
2) ~STATIC_CRT~ is deprecated, use new `AWS_STATIC_MSVC_RUNTIME_LIBRARY` option instead.
3) Use `$<CONFIG>` generator expressions, instead of checking `${CMAKE_BUILD_TYPE}`, to better support multi-config generators like Visual Studio. See: https://cmake.org/cmake/help/v3.22/manual/cmake-buildsystem.7.html#build-configurations
> Fix CMake option for choosing MSVC runtime library

- include/aws/iot/Mqtt5Client.h
- source/iot/Mqtt5Client.cpp
Found this inconsistency when trying to build a Mqtt5Client.
Setting the bootstrap is available when using Mqtt5ClientOptions directly but it was missing from Mqtt5ClientBuilder.
-----------------------
> Add Mqtt5ClientBuilder method to set bootstrap

- include/aws/crt/mqtt/Mqtt5Packets.h
- source/mqtt/Mqtt5Packets.cpp
While exploring what was being provided by `NegotiatedSettings`, I noticed that some methods were misspelled.
----------------------
> Fix typo on NegotiatedSettings (Avaliable->Available)

- include/aws/crt/mqtt/private/Mqtt5ClientCore.h
- include/aws/crt/mqtt/private/MqttConnectionCore.h
- source/mqtt/Mqtt5ClientCore.cpp
- source/mqtt/MqttConnectionCore.cpp
The doxygen would fail on the functions that was declared in private header as it could not find the function declaration. Disable doxygen for files with private headers. 
> Disable doxygen for private header API

- CMakeLists.txt
*Issue #:* https://github.com/awslabs/aws-crt-cpp/issues/548
> Fix CMake error when BUILD_DEPS=OFF

- include/aws/crt/mqtt/Mqtt5Client.h
- include/aws/crt/mqtt/Mqtt5Packets.h
- include/aws/iot/Mqtt5Client.h
- source/iot/Mqtt5Client.cpp
- source/mqtt/Mqtt5Client.cpp
- source/mqtt/Mqtt5Packets.cpp
> Mqtt5 Topic aliasing support

- bin/mqtt5_canary/main.cpp
> Fix mqtt5 canary memory leak

- tests/CMakeLists.txt
- tests/Mqtt5ClientTest.cpp
> Test Shared Subscription

- source/mqtt/Mqtt5ClientCore.cpp
Currently, `subscribe`, `unsubscribe`, and `publish` operations are enqueued with overridden timeouts set to garbage values.
This PR fixes it by explicitly setting the overridden timeout to 0.
> Fix overridden timeout values for mqtt5 operations

- source/crypto/SymmetricCipher.cpp
A [recent change](https://github.com/awslabs/aws-crt-cpp/commit/8b839ff63e705042d93b88c38a48d27e181d95ec) added symmetric ciphers to the crt.
it added the call
```
aws_aes_gcm_256_new(
allocator,
key.has_value() ? &key.value() : nullptr,
iv.has_value() ? &iv.value() : nullptr,
tag.has_value() ? &tag.value() : nullptr,
aad.has_value() ? &aad.value() : nullptr)
```
whereas in c-cal it is actually defined as 
```
AWS_CAL_API struct aws_symmetric_cipher *aws_aes_gcm_256_new(
struct aws_allocator *allocator,
const struct aws_byte_cursor *key,
const struct aws_byte_cursor *iv,
const struct aws_byte_cursor *aad,
const struct aws_byte_cursor *decryption_tag);
```
so we are passing the wrong values to aad and tag, they are swapped around, this fixes the order.
By …
> fix order of arguments when calling aws_aes_gcm_256_new

- include/aws/crt/Variant.h
- tests/CMakeLists.txt
result of short + short is always an int (one of those weird c++ standard quirks), so when we write the result back to a short field some compilers might raise a warning for it if -Wconversion is on (which it is typically not, since its not part of -Wall, etc...). So be more explicit casting back
> make variant index casts more explicit

- source/io/SocketOptions.cpp
Update to latest submodules:
```
aws-c-cal          v0.7.0 -> v0.7.1
aws-c-io           v0.14.9 -> v0.14.11
aws-c-http         v0.8.2 -> v0.8.3
aws-c-s3           v0.5.10 -> v0.6.1
aws-lc             v1.30.1 -> v1.31.0
s2n                v1.4.16 -> v1.4.17
```
Fix comes from here: https://github.com/awslabs/aws-c-io/pull/652
> Fix memory leaks in Windows TLS handler 

- include/aws/crt/StringView.h
[Currently CI is failing mainline on msvc with](https://github.com/awslabs/aws-crt-cpp/actions/runs/10619842225/job/29438306844)
```
D:\a\work\aws-crt-cpp\include\aws\crt\StringView.h(861,51): error C2760: syntax error: '>' was unexpected here; expected 'declaration' [D:\a\work\aws-crt-cpp\build\aws-crt-cpp\aws-crt-cpp-header-check-cxx20.vcxproj]
(compiling source file '../../header-checker-cxx20/headerchecker_aws_crt_Api_h.cpp')
```
fixes [most vexing parse](https://en.wikipedia.org/wiki/Most_vexing_parse) by adding braced init + include string directly.
> fix MSVC most vexing parse

- CMakeLists.txt
- include/aws/crt/checksum/CRC.h
- include/aws/crt/crypto/Hash.h
- source/checksum/CRC.cpp
- tests/CRCTest.cpp
> Bind out CRC64

- .github/workflows/ci.yml
- CMakeLists.txt
- Prebuild S2N and update submodule for using s2n_cleanup_thread() 
> prebuild s2n

- .github/workflows/ci.yml
- CMakeLists.txt
- include/aws/crt/StlAllocator.h
**Issue:**
When building with GCC 4.8 and 4.9 and `-DBUILD_SHARED_LIBS=ON`, many tests were crashing. The crashes would say something like "free(): invalid pointer" and the stack trace would point into the c++ string headers.
**Things we tried**
- Crash stopped if we commented out the [recently-added line in CMakeLists.txt](https://github.com/awslabs/aws-crt-cpp/blob/80f4736126e14223a0c3882d3b734607143731f3/CMakeLists.txt#L305) line that sets `CXX_VISIBILITY_PRESET hidden`. So obviously symbol visibility has something to do with it.
- We tried adding adding `AWS_CRT_CPP_API` to the templated `StlAllocator` class (see https://github.com/awslabs/aws-crt-cpp/pull/675/commits/edfed1419841cd20bd21c0421861329f2deb2aad), which stopped GCC 4.x from crashing, but then the [Windows compiler didn't …
> Fix crashes in GCC 4.x shared-libs builds, due to recent symbol visibility changes

- .github/workflows/ci.yml
- CMakeLists.txt
**Issue:**
A user had been building aws-crt-cpp with `CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0`, and that worked fine until the recent change where we started hiding symbols by default (PR https://github.com/awslabs/aws-crt-cpp/pull/666)
With symbols hidden by default, and `_GLIBCXX_USE_CXX11_ABI=0`, tests would crash in the destructor of `Aws::Crt::String` (which is `std::string` with a custom allocator).
Don't hide symbols when building for the ancient glibcxx ABI.
I don't 100% understand why this fixes the issue, but the situation is esoteric enough that it doesn't seem worth spending more days on this problem.
**Background**
See: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
GCC had to introduce a new ABI for C++11 which removed the …
> Fix crash when building with _GLIBCXX_USE_CXX11_ABI=0

- include/aws/iot/MqttRequestResponseClient.h
- source/iot/MqttRequestResponseClient.cpp
- tests/MqttRequestResponse.cpp
Service client might need a topic where a stream's publish message was received.
Description of changes:
Add a topic argument to incoming publish callback.
> Add topic argument to publish callback in request-response stream client

- .github/workflows/ci.yml
We rely on qemu to test aarch64 on x86-64 github runners.
Qemu had a bug where they had a bug with incorrectly mapping address space. That mostly worked fine until kernel patch that increased entropy in their address randomization. TLDR; qemu likes to segfault a lot against new kernels on our aarch64 test. Solution is to switch to a different github qemu user static image that forces a latest version of qemu, that has the bug fixed.
if you want to read more - https://github.com/tonistiigi/binfmt/issues/240
> Fix Arm based ci steps

- source/Types.cpp
**Issue:**
aws-sdk-cpp needs to send streaming requests of unknown content length. This isn't currently supported in our HTTP/1 client.
- Update submodules:
aws-c-auth         v0.8.5 -> v0.8.6
aws-c-cal          v0.8.3 -> v0.8.7
aws-c-common       v0.11.1 -> v0.12.0
aws-c-event-stream v0.5.2 -> v0.5.4
aws-c-http         v0.9.3 -> v0.9.5
aws-c-io           v0.16.0 -> v0.17.0
aws-c-s3           v0.7.11 -> v0.7.13
aws-lc             v1.46.1 -> v1.48.4
s2n                v1.5.13 -> v1.5.14
- Bring in change that allows HTTP/1 streams of unknown length:
- https://github.com/awslabs/aws-c-http/pull/506
- Remove hack in Base64 decoded logic, which is no longer necessary due to this change:
- https://github.com/awslabs/aws-c-common/pull/1188
By submitting this pull …
> HTTP/1: Support streaming requests of unknown length

- tests/CborTest.cpp
**Issue:**
Rare random failure of  "CborTimeStampTest" (see [logs](https://github.com/awslabs/aws-crt-cpp/actions/runs/13912044756/job/38928108124?pr=717#step:3:3011))
**Diagnosis:**
This test does:
- get timestamp from current `std::chrono::time_point<std::chrono::system_clock>
- CBOR encode timestamp as seconds-as-64bit-floating-point
- decode timestamp
- compare original timestamp with encoded/decoded timestam
- deal with floating point precision differences by casting to milliseconds-as-integer before comparing
The flow above seems good. There are some differences in floating point precision, but we ultimately compare the values at lower precision (milliseconds-as-integer). So what's up???
Fix helper function that loses lots of precision, due to too much …
> Fix flaky CBOR test

- tests/HttpClientConnectionManagerTest.cpp
N/A
Use latest PQ TLS Cipher Preference in Tests.
> Use latest PQ TLS Cipher Preference in Tests

- .github/workflows/ci.yml
**Issue:**
The "std-compat" CI isn't doing what it's supposed to: building aws-crt-cpp with different versions of the C++ std.
It broke accidentally when [this commit](https://github.com/awslabs/aws-crt-cpp/commit/eaaaa60e3810ae33435c08c515f0be888e1af55d) stopped passing `--env CXXFLAGS` to the container.
Fix it, so C++ version is passed to the container.
Set it via `CMAKE_CXX_STANDARD=11`, instead of via `CXXFLAGS=-std=c++11`, since this is the "more correct" way to tell CMake the C++ standard you want. Doing it via `CXXFLAGS=-std=c++11` can (depending on the version of CMake you're using) force compiler extensions to be disabled.
> Fix "std-compat" CI to actually test what it's supposed to

- source/Api.cpp
Update submodules, bringing in this notable fix:
- https://github.com/awslabs/aws-c-io/pull/718
```
aws-c-auth         v0.8.6 -> v0.9.0
aws-c-cal          v0.8.7 -> v0.8.8
aws-c-common       v0.12.0 -> v0.12.2
aws-c-io           v0.17.0 -> v0.17.1
aws-checksums      v0.2.3 -> v0.2.5
aws-lc             v1.48.4 -> v1.48.5
s2n                v1.5.14 -> v1.5.15
```
> Fix IP address being labelled "bad" for too long

- include/aws/crt/UUID.h
- source/UUID.cpp
Comparison operators in `UUID` don't have `const` specifier. For the C++20 standard, this leads to the following warning:
```
/home/runner/work/***/***/aws-crt-cpp/tests/UUIDTest.cpp:22:26: error: ISO C++20 considers use
of overloaded operator '==' (with operand types 'Aws::Crt::UUID' and 'Aws::Crt::UUID') to be ambiguous
despite there being a unique best viable function [-Werror,-Wambiguous-reversed-operator]
```
The reason is C++20 rules for generating reversed oeprators: https://timsong-cpp.github.io/cppwp/n4861/over.match#oper-3.4.4
See a live example: https://godbolt.org/z/PcEqY7x5z
**NOTE**: The warning for `UUID` appears only for clang-13, clang-14, and clang-15. In clang-16, they resolved
the `-Wambiguous-reversed-operator` warning for cases when a …
> Add const specifier to UUID comparison operators

- .github/workflows/ci.yml
- tests/MqttRequestResponse.cpp
Bump up the operation timeout for Request Response client test from 5 seconds to 30. 
MqttRequestResponse_UpdateNamedShadowSuccessAccepted311 was potentially failing due to the timeout on a successful subscribe not receiving a suback within 5 seconds.
> Increase Operation Timeout in CI for Req/Resp Tests

- .github/workflows/ci.yml
- include/aws/crt/mqtt/Mqtt5Client.h
- include/aws/crt/mqtt/private/Mqtt5ClientCore.h
- include/aws/iot/Mqtt5Client.h
LLVM recently added a [new warning](https://github.com/llvm/llvm-project/pull/131188) for virtual methods in final classes. Mqtt5Client and Mqtt5ClientOptions are final and have virtual members, so they trigger this warning. Fixed it and add compiler validation for clang21
> Fix warnings for latest LLVM compiler update

- include/aws/crt/auth/Credentials.h
- source/auth/Credentials.cpp
- tests/CMakeLists.txt
- tests/CredentialsTest.cpp
Adds a binding for [`credentials_provider_sts_web_identity.`](https://github.com/awslabs/aws-c-auth/blob/main/include/aws/auth/credentials.h#L1166-L1177). almost identical to what we have for the normal [STS provider](https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/auth/Credentials.h#L570-L575).
> add binding for sts web identity provider

- include/aws/crt/auth/Credentials.h
- source/auth/Credentials.cpp
- tests/CredentialsTest.cpp
Coming from https://github.com/aws/aws-sdk-cpp/pull/3505 its apparently that `TlsContext` should be `TlsConnectionOptions` instead as that is what the SDK overrides, and `TlsContext` has a helper method to spawn new connection options but not the other way around. This is acutally how it is also done in [`CredentialsProviderX509Config`](https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/auth/Credentials.h#L312)
> update web identity context to use connection options instead of context

- .github/workflows/ci.yml
Set fail-fast to false on all CI jobs using a matrix. This will allow us to better track what is failing and why.
> CI Jobs fail-fast False

- source/cbor/Cbor.cpp
- tests/CMakeLists.txt
- tests/CborTest.cpp
CborDecoder initialize m_lastError in constructor to AWS_ERROR_SUCCESS instead of it holding a garbage value
> CborDecoder initialize m_lastError in constructor
