- README.md
> Added additional sample docs

- samples/mqtt_pub_sub/main.cpp
> Fixed occasional hang in sample

- aws-common-runtime/CMakeLists.txt
- codebuild/linux-gcc-4x-x86.yml
- samples/mqtt_pub_sub/main.cpp
> Fixes to make pubsub sample compatible with greengrasscore.

- aws-common-runtime/CMakeLists.txt
> Updated http and mqtt tags.

- include/aws/crt/Optional.h
- samples/mqtt_pub_sub/main.cpp
> Fixed build error in mqtt pub sub sample.

- aws-common-runtime/CMakeLists.txt
- include/aws/crt/http/HttpConnection.h
- include/aws/crt/http/HttpConnectionManager.h
- source/http/HttpConnection.cpp
- source/http/HttpConnectionManager.cpp
- tests/HttpClientConnectionManagerTest.cpp
> Updated dependencies to latest versions.

- aws-common-runtime/CMakeLists.txt
- include/aws/crt/mqtt/MqttClient.h
- source/mqtt/MqttClient.cpp
> Updated mqtt to latest version with more logging.

- aws-common-runtime/CMakeLists.txt
> Another update.

- include/aws/crt/JsonObject.h
- include/aws/crt/external/cJSON.h
- source/external/cJSON.cpp
> Namespace wrap CJSON

- include/aws/crt/auth/Credentials.h
- source/auth/Credentials.cpp
- source/io/Bootstrap.cpp
- tests/CMakeLists.txt
- tests/CredentialsTest.cpp
> Credentials and credentials provider bindings

- aws-common-runtime/CMakeLists.txt
These updates make sure that the proper info is returned for all error codes.
> Update dependencies to fix error info desync

- aws-common-runtime/CMakeLists.txt
*Issue #, if available:* https://github.com/awslabs/aws-crt-cpp/issues/38
*Description of changes:* Will update with released versions when upstream PRs are merged
> aws-c-common and s2n pointed at pending pthreads changes

- aws-common-runtime/CMakeLists.txt
- source/Api.cpp
- source/io/TlsOptions.cpp
> Updates CRT for library init changes

- aws-common-runtime/CMakeLists.txt
- include/aws/crt/mqtt/MqttClient.h
- samples/mqtt_pub_sub/main.cpp
- source/mqtt/MqttClient.cpp
- tests/MqttClientTest.cpp
> On any publish support

- CMakeLists.txt
> Update version string to the tag that will be following.

- aws-common-runtime/CMakeLists.txt
> Updated to latest aws-c-io to pick up a windows security fix.

- source/auth/Sigv4Signing.cpp
> Fixed stupid error from not checking error codes in signing callbacks.

- samples/mqtt_pub_sub/main.cpp
- samples/raw_mqtt_pub_sub/main.cpp
- tests/IotServiceTest.cpp
Building the project with Visual Studio 2019 currently fails due to compiler warnings treated as errors, and these fixes should address them.
---
> Fix MSVC compiler warnings

- source/mqtt/MqttClient.cpp
> Fixed anyCbData pointer not being properly initialized in all paths.

- aws-common-runtime/CMakeLists.txt
- source/io/Bootstrap.cpp
> Update to latest deps, and pick up mqtt leak fix.

- aws-common-runtime/CMakeLists.txt
> Stream leak fix

- CMakeLists.txt
submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
> Do not default build types on windows.

- .github/workflows/ci.yml
- .gitmodules
- builder.json
> Fixes to allow ARM to cross compile

- .github/workflows/ci.yml
- CMakeLists.txt
Clone of https://github.com/awslabs/aws-crt-cpp/pull/100
> Hide CJSON symbols

- CMakeLists.txt
> Forgot to update the version number.

- .github/workflows/ci.yml
- builder.json
Depends on
* https://github.com/awslabs/s2n/pull/1714 (waiting for approval)
* https://github.com/awslabs/aws-c-http/pull/208 (done)
* https://github.com/awslabs/aws-c-common/pull/614 (done)
* https://github.com/awslabs/aws-crt-builder/pull/35 (v0.6.1)
> Android support

- source/UUID.cpp
- tests/CMakeLists.txt
- tests/UUIDTest.cpp
> UUID ToString & test

- tests/HttpClientConnectionManagerTest.cpp
Updating aws-c-* dependencies and fixing unit test.
> Updating aws-c-* dependencies

- README.md
*Issue #, if available:* https://github.com/awslabs/aws-crt-cpp/pull/117
> Update to get static CRT support from aws-c-common, doc update

- .github/workflows/ci.yml
*Issue #, if available:* https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/119
> Added job for Windows+VC14

- .github/workflows/release.yml
- update-version.sh
> Added a job that updates version in CMakeLists.txt when a new tag is created

- .github/workflows/release.yml
> Removed filtering on when release job runs

- .github/workflows/release.yml
- update-version.sh
> Fixed sed version update

- .github/workflows/release.yml
- update-version.sh
> Fixed git diff check in release action

- .github/workflows/release.yml
- update-version.sh
> Fixed version update action

- update-version.sh
> Added git config to update-version script

- update-version.sh
> Fixed push remote in update script

- .github/workflows/release.yml
- update-version.sh
> Pass github token to update script

- .github/workflows/release.yml
> Fixed checkout config for update script

- update-version.sh
> Fixing automated push

- update-version.sh
> Fixed sed regex

- update-version.sh
> Fixed force push for updated version

- .github/workflows/ci.yml
> Added jobs for compiling against all supported C++ standards

- .github/workflows/release.yml
- update-version.sh
*Issue #, if available:* https://github.com/awslabs/aws-crt-cpp/issues/143
> Only update git tags on release, not create

- README.md
Adding version to log message info.
> TLS ReadMe Fix

- include/aws/crt/Types.h
- include/aws/crt/auth/Sigv4Signing.h
- source/Types.cpp
- source/auth/Sigv4Signing.cpp
- source/iot/MqttClient.cpp
- tests/CMakeLists.txt
- tests/Sigv4SigningTest.cpp
This allows precalculated hashes to be used.
Stemming from changes here: https://github.com/awslabs/aws-c-auth/pull/97
> AwsSigningConfig.SetSignedBodyValue() takes string instead of enum

- include/aws/crt/io/Bootstrap.h
- source/io/Bootstrap.cpp
> Ensure bootstrap callback data is allocated/freed with bootstrap's allocator

- include/aws/crt/StringView.h
- include/aws/crt/Types.h
- tests/CMakeLists.txt
- tests/HostResolverTest.cpp
- tests/IotServiceTest.cpp
- tests/StringViewTest.cpp
> Support string_view

- .github/workflows/ci.yml
- source/Api.cpp
> Update to builder v0.7.0

- .github/workflows/ci.yml
- cmake/AwsCheckHeadersCxx.cmake
- include/aws/crt/StringView.h
- source/io/HostResolver.cpp
* Updates host resolver creation to new interface
> Update host resolver creation to new interface

- .github/workflows/ci.yml
- CONTRIBUTING.md
- docsrc/Doxyfile
> find/replace: master->main

- source/io/TlsOptions.cpp
* Update submodules to bring in bug fixes required for nested tls (via proxy)
* Fix a tls connection options constructor bug wrt setting the allocator
> Nested tls support

- include/aws/crt/http/HttpProxyStrategy.h
- source/http/HttpProxyStrategy.cpp
Break NTLM strategy into 2 components/different strategies
> Proxy request flow no one time strategy

- include/aws/crt/mqtt/MqttClient.h
- source/mqtt/MqttClient.cpp
This is a backwards compatible change.
Mark existing `OnPublishReceivedHandler` deprecated, replace with `OnMessageReceivedHandler`. New handler carries 3 more args: `retain`, `qos`, and `dup`. Mark functions that take old handler as deprecated, and add otherwise identical function that accept new handler.
> Add retain, dup, qos to MQTT on-message callback.

- include/aws/crt/mqtt/MqttClient.h
- source/mqtt/MqttClient.cpp
> timeout binding

- include/aws/crt/io/TlsOptions.h
- source/io/TlsOptions.cpp
CI trigger for https://github.com/awslabs/aws-crt-cpp/pull/224
> Verify TlsConnectionOptions (awslabs#223)

- .github/workflows/ci.yml
- CMakeLists.txt
- README.md
- builder.json
- codebuild/common-posix.sh
- codebuild/common-windows.bat
> BUILD_DEPS=ON by default

- source/mqtt/MqttClient.cpp
> deep copy of the payload for user

- update-version.sh
> Github cli test

- CMakeLists.txt
> AutoTag PR for v0.15.4

- CMakeLists.txt
> AutoTag PR for v0.15.5

- CMakeLists.txt
> AutoTag PR for v0.15.6

- CMakeLists.txt
> AutoTag PR for v0.16.0

- CMakeLists.txt
> AutoTag PR for v0.16.1

- CMakeLists.txt
> AutoTag PR for v0.16.2

- update-version.sh
> I think I've been stomping myself

- CMakeLists.txt
> AutoTag PR for v0.16.3

- update-version.sh
> Remove git state debugging output and check if the tag pull is necessary by disabling it temporarily

- CMakeLists.txt
> AutoTag PR for v0.16.4

- update-version.sh
> Remove unnecessary tag fetch and update commenting

- CMakeLists.txt
> AutoTag PR for v0.17.0

- .github/workflows/ci.yml
Get new features via submodule updates:
- Set new build flag `-DUSE_CPU_EXTENSIONS=OFF` to disable CPU-specific function implementations
- Support for HTTP_PROXY and HTTPS_PROXY environment variables
Also, add new CI runs for `-DUSE_CPU_EXTENSIONS=OFF` and 
Submodules updated:
- aws-c-auth: v0.6.1 -> v0.6.4
- aws-c-cal: v0.5.11 -> v0.5.12
- aws-c-common: v0.6.9 -> v0.6.11
- aws-c-http: v0.6.5 -> v0.6.7
- aws-c-s3: v0.1.23 -> v0.1.26
- aws-checksums: v0.1.11 -> v0.1.12
> New build flag: -DUSE_CPU_EXTENSIONS=OFF

- CMakeLists.txt
> AutoTag PR for v0.17.1

- CMakeLists.txt
> AutoTag PR for v0.17.5

- CMakeLists.txt
> AutoTag PR for v0.17.8

- CMakeLists.txt
> AutoTag PR for v0.17.9

- CMakeLists.txt
> AutoTag PR for v0.17.10

- CMakeLists.txt
> AutoTag PR for v0.17.11

- CMakeLists.txt
> AutoTag PR for v0.17.12

- .builder/actions/build_crt.py
- .github/workflows/ci.yml
- bin/elasticurl_cpp/main.cpp
- builder.json
- include/aws/crt/io/TlsOptions.h
- include/aws/iot/MqttClient.h
- source/io/TlsOptions.cpp
- source/io/Uri.cpp
- tests/CMakeLists.txt
**Issue:**
iOS builds were broken
**Description of Changes:**
- The platform-specific TLS functions have changed so that they're runtime errors now, instead of compile-time errors. This is easier to maintain. See: https://github.com/awslabs/aws-c-io/pull/460
- Run iOS build in CI
-  Use `build_crt.py` python script to control the cmake args used in CI. The old way of using `builder.json` was accidentally removing cmake args. For example, before this change `-DENABLE_SANITIZERS=ON` was always being removed, and we didn't realize that some tests were actually leaking memory.
- Fix elasticurl, which broke due to changes in the command-line parser, see: https://github.com/awslabs/aws-c-common/pull/878
Also, add iOS build to CI. At this time, the tests aren't run. But at least we can be sure …
> Fix iOS builds

- CMakeLists.txt
> AutoTag PR for v0.17.13

- CMakeLists.txt
> AutoTag PR for v0.17.15

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
> fix CI to use tag image instead latest

- CMakeLists.txt
> AutoTag PR for v0.17.16

- bin/elasticurl_cpp/main.cpp
> try to fix the elasticurl(short term)

- CMakeLists.txt
> AutoTag PR for v0.17.18

- .github/workflows/ci.yml
- builder.json
> add linux-openssl-static workflow to build ci.yml

- CMakeLists.txt
> AutoTag PR for v0.17.19

- source/Api.cpp
> Forcing uint16_t on call to event loop

- CMakeLists.txt
> AutoTag PR for v0.17.20

- CMakeLists.txt
> AutoTag PR for v0.17.21

- CMakeLists.txt
> AutoTag PR for v0.17.22

- CMakeLists.txt
> AutoTag PR for v0.17.23

- CMakeLists.txt
> AutoTag PR for v0.17.24

- CMakeLists.txt
> AutoTag PR for v0.17.25

- CMakeLists.txt
> AutoTag PR for v0.17.26

- CMakeLists.txt
> AutoTag PR for v0.17.27

- CMakeLists.txt
> AutoTag PR for v0.17.28

- CMakeLists.txt
> AutoTag PR for v0.17.29

- CMakeLists.txt
> AutoTag PR for v0.17.30

- CMakeLists.txt
> AutoTag PR for v0.18.2

- CMakeLists.txt
> AutoTag PR for v0.18.3

- CMakeLists.txt
> AutoTag PR for v0.18.4

- CMakeLists.txt
> AutoTag PR for v0.18.5

- CMakeLists.txt
> AutoTag PR for v0.18.6

- CMakeLists.txt
> AutoTag PR for v0.18.7

- .builder/actions/build_crt.py
- .builder/actions/crt-ci-prep.py
- .github/workflows/ci.yml
- builder.json
- include/aws/crt/auth/Credentials.h
- include/aws/crt/io/TlsOptions.h
- source/auth/Credentials.cpp
- tests/CMakeLists.txt
- tests/CredentialsTest.cpp
* Cognito credentials provider binding
* STS credentials provider binding
> Cognito provider

- CMakeLists.txt
> AutoTag PR for v0.18.8

- include/aws/crt/endpoints/RuleEngine.h
- source/endpoints/RuleEngine.cpp
remove unused argument to fix build warning on some compilers.
> Build warning

- include/aws/crt/endpoints/RuleEngine.h
- source/endpoints/RuleEngine.cpp
Remove another unused variable causing build issues
> remove another unused varaible

- source/mqtt/MqttClient.cpp
> Bound strlen call by maximum topic length

- source/mqtt/Mqtt5Packets.cpp
In `ConnectPacket::initializeRawOptions` the wrong Optional was queried, if having a value.
> Wrong optional was queried.

- CMakeLists.txt
> Generate files in build directory

- include/aws/crt/mqtt/Mqtt5Packets.h
- source/mqtt/Mqtt5Packets.cpp
> Bind missing negotiated setting fields

- bin/mqtt5_canary/main.cpp
Setup a 0 tps option for no transaction limits
> Mqtt5 Canary Improvment

- source/io/HostResolver.cpp
does not check if ptr is null
check if hostAddresses is not a null ptr.
> Fix host resolve on a non-existent host

- README.md
- bin/elasticurl_cpp/main.cpp
- bin/mqtt5_app/main.cpp
- bin/mqtt5_canary/main.cpp
- include/aws/crt/http/HttpConnection.h
- include/aws/crt/io/Uri.h
- include/aws/crt/mqtt/Mqtt5Client.h
- include/aws/crt/mqtt/MqttClient.h
- include/aws/crt/mqtt/MqttTypes.h
- include/aws/crt/mqtt/private/MqttConnectionCore.h
- include/aws/iot/Mqtt5Client.h
- include/aws/iot/MqttClient.h
- source/io/Uri.cpp
- source/iot/Mqtt5Client.cpp
- source/iot/MqttClient.cpp
- source/mqtt/Mqtt5Client.cpp
- source/mqtt/MqttClient.cpp
- tests/CredentialsTest.cpp
- tests/Mqtt5ClientTest.cpp
- tests/MqttClientTest.cpp
- tests/ProxyTest.cpp
Issue: https://github.com/awslabs/aws-c-io/issues/576
> Change `port` from uint16_t to uint32_t, to support VSOCK

- .github/workflows/ci.yml
> Crt version bump

- source/mqtt/Mqtt5Packets.cpp
- tests/CMakeLists.txt
- tests/Mqtt5ClientTest.cpp
> Fix memory leak when UnsubscribePacket is reused

- include/aws/crt/crypto/SymmetricCipher.h
- source/Types.cpp
- source/crypto/SymmetricCipher.cpp
- tests/SymmetricCipherTest.cpp
Updates to aes interface to reflect low level changes.
Waring: breaks backward compat.
> Update aes interface

- include/aws/crt/endpoints/RuleEngine.h
- source/endpoints/RuleEngine.cpp
- tests/RuleEngineTest.cpp
> Add support for string array ep context params

- include/aws/iot/Mqtt5Client.h
- source/iot/Mqtt5Client.cpp
> Expose socket options from Mqtt5ClientBuilder

- include/aws/crt/Variant.h
Fixes a typo in variant that made visit not usable
> Fix typo in variant

- .github/workflows/ci.yml
- Latest sub-modules and builder
> Fix Openssl Compile and Runtime Version Mismatch

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
> Switch CI to using roles

- tests/RuleEngineTest.cpp
https://github.com/awslabs/aws-c-sdkutils/issues/54
- Latest submodules
- Fix Endpoint resolver test 
> Fix Endpoint Resolver Test By Escpaing "-"

- bin/mqtt5_canary/main.cpp
> Update eventstream submodule:

- .github/workflows/ci.yml
Add ci and fix for lean and mean windows headers
> Bump crt latest versions
